# Generated by Django 3.2.5 on 2023-10-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cate_img',
            field=models.ImageField(default='cate.jpg', upload_to='cate'),
        ),
    ]
