# Generated by Django 3.2.5 on 2023-10-12 08:10

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='images',
            field=models.ImageField(default='product.jpg', upload_to='product-images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=product.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='image',
            field=models.ImageField(default='vendor.jpg', upload_to=product.models.user_directory_path),
        ),
    ]
