# Generated by Django 3.2.5 on 2023-10-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivery')], default='process', max_length=50),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivery')], default='process', max_length=50),
        ),
    ]
