# Generated by Django 3.2.5 on 2023-10-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=3, default='1000', max_digits=9),
        ),
    ]
