# Generated by Django 3.2.5 on 2023-10-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20231025_0737'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'CartOrderProduct'},
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
